language: python
python:
  - 2.7.11
  - 3.5.1
virtualenv:
  system_site_package: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - echo $TRAVIS_PYTHON_VERSION
  - pip install -U pytest-cov
  - pip install -U h5py Pillow six numpy
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5* ]]; then travis_retry pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp35-cp35m-linux_x86_64.whl; fi
  - python setup.py install

script:
  - python setup.py test

matrix:
  fast_finish: true